language: node_js # (1)
node_js:
  - "8"
services:
  - docker # (2)
  - postgresql
jobs:
  include:
    - stage: test
      env:
        global:
          - NODE_ENV=test
      before_script:
        - npm install
        - npm run build
        - npm install -g sequelize-cli
        - sequelize db:migrate
      script:
        - npm test # (4)
      after_success:
        - npm run coverage
    - stage: docker-deploy-image # (5)
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t rianreis/$APP .
        - docker push rianreis/$APP
    - stage: deploy
      script: skip
      deploy: # (6)
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: "us-east-1"
        app: "gce"
        env: "$APP"
        bucket_name: "elasticbeanstalk-us-east-1-526564402012"
        bucket_path: "$APP"
